spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://localhost:1111
            predicates:
              - Path=/api/users/**

          - id: auth-service
            uri: http://localhost:1111
            predicates:
              - Path=/api/auth/**

          - id: product-service
            uri: http://localhost:2222
            predicates:
              - Path=/api/products/**

          - id: order-service
            uri: http://localhost:3333
            predicates:
              - Path=/api/orders/**

          - id: admin-service
            uri: http://localhost:4444
            predicates:
              - Path=/api/admin/**

          - id: cart-service
            uri: http://localhost:5555
            predicates:
              - Path=/api/cart/**
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

server:
  port: 9999