spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: quizuser
    password: quizpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 1111