spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: quizuser
    password: quizpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 2222